---
driver:
  name: vagrant
  network:
    - ["private_network", { type: "dhcp" }]

provisioner:
  name: chef_zero

platforms:
  - name: windows-2008r2
    driver_config:
      box: opentable/win-2008r2-datacenter-amd64-nocm
      vm_hostname: w2012R1
      communicator: winrm
      gui: true
    transport:
      name: winrm
  - name: windows-2012r2
    driver_config:
      box: opentable/win-2012r2-standard-amd64-nocm
      vm_hostname: w2012R1
      communicator: winrm
      gui: true
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[wua_updater::default]
    attributes:
