name 'wua_updater'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures wua_updater'
long_description 'Installs/Configures wua_updater'
version '0.1.0'
